blog/urls.py
from django.urls import path

from . import views

app_name = 'weblog'
urlpatterns = [
    path(
        '<int:year>/<str:month>/<int:day>/<slug>/',
        views.BlogDateDetailView.as_view(),
        name="entry"
    ),
    path(
        '<int:year>/<str:month>/<int:day>/',
        views.BlogDayArchiveView.as_view(),
        name="archive-day"
    ),
    path(
        '<int:year>/<str:month>/',
        views.BlogMonthArchiveView.as_view(),
        name="archive-month"
    ),
    path(
        '<int:year>/',
        views.BlogYearArchiveView.as_view(),
        name="archive-year"
    ),
    path(
        '',
        views.BlogArchiveIndexView.as_view(),
        name="index"
    ),
]

django_website/urls.py
from __future__ import absolute_import

from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
from django.contrib.comments.feeds import LatestCommentFeed
from django.contrib.comments.models import Comment
from django.contrib.sitemaps import views as sitemap_views
from django.views.decorators.cache import cache_page
from .aggregator.feeds import CommunityAggregatorFeed
from .aggregator.models import FeedItem
from .blog.feeds import WeblogEntryFeed
from .sitemaps import FlatPageSitemap, WeblogSitemap

comments_info_dict = {
    'queryset': Comment.objects.filter(is_public=True).order_by('-submit_date'),
    'paginate_by': 15,
}

feeds = {
    'weblog': WeblogEntryFeed,
    'comments': LatestCommentFeed,
    'community': CommunityAggregatorFeed,
}

sitemaps = {
    'weblog': WeblogSitemap,
    'flatpages': FlatPageSitemap,
}

urlpatterns = patterns('',
    url(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'homepage.html'}, name="homepage"),
    (r'^accounts/', include('django_website.apps.accounts.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^comments/$', 'django.views.generic.list_detail.object_list', comments_info_dict),
    (r'^comments/', include('django.contrib.comments.urls')),
    url(r'^community/add/(?P<feed_type_slug>[-\w]+)/',
         'django_website.apps.aggregator.views.add_feed',
          name='community-add-feed'),
    url(r'^community/(?P<feed_type_slug>[-\w]+)/',
         'django_website.apps.aggregator.views.feed_list',
          name="community-feed-list"),
    url(r'^community/', 'django_website.apps.aggregator.views.index', name='community-index'),
    (r'^contact/', include('django_website.apps.contact.urls')),
    (r'^documentation/', include('django_website.legacy.docurls')),
    (r'^r/', include('django.conf.urls.shortcut')),
    (r'^rss/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    (r'^sitemap\.xml$', cache_page(sitemap_views.sitemap, 60 * 60 * 6), {'sitemaps': sitemaps}),
    (r'^weblog/', include('django_website.blog.urls')),
    (r'^freenode\.9xJY7YIUWtwn\.html$', 'django.views.generic.simple.direct_to_template', {'template': 'freenode_tmp.html'}),
    url(r'^download$', 'django.contrib.flatpages.views.flatpage', {'url': 'download'}, name="download"),
)

if settings.DEVELOPMENT_MODE:
    urlpatterns += patterns("django.views",
        url(r"^media/(?P<path>.*)", "static.serve", {
            "document_root": settings.MEDIA_ROOT,
        }),
    )

urlpatterns += patterns('',
    # flatpages need to be last b/c they match anything
    (r'', include('django.contrib.flatpages.urls')),
)

admin.autodiscover()

fundraising/urls.py
from django.urls import path

from . import views

app_name = 'fundraising'
urlpatterns = [
    path('', views.index, name='index'),
    path('donate/', views.donate, name='donate'),
    path('thank-you/<donation>/', views.thank_you, name='thank-you'),
    path('manage-donations/<hero>/', views.manage_donations, name='manage-donations'),
    path('manage-donations/<hero>/cancel/', views.cancel_donation, name='cancel-donation'),
    path('receive-webhook/', views.receive_webhook, name='receive-webhook'),
    path('update-card/', views.update_card, name='update-card'),
]

fundraising/models.py
import datetime
from decimal import Decimal

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import crypto, timezone
from django_hosts.resolvers import reverse
from sorl.thumbnail import ImageField, get_thumbnail

GOAL_AMOUNT = Decimal("200000.00")
GOAL_START_DATE = datetime.date(datetime.datetime.today().year, 1, 1)
DISPLAY_DONOR_DAYS = 365
DEFAULT_DONATION_AMOUNT = 50
LEADERSHIP_LEVEL_AMOUNT = Decimal("1000.00")
INTERVAL_CHOICES = (
    ('monthly', 'Monthly donation'),
    ('quarterly', 'Quarterly donation'),
    ('yearly', 'Yearly donation'),
    ('onetime', 'One-time donation'),
)


class DjangoHeroManager(models.Manager):
    def for_public_display(self):
        donors = self.get_queryset().filter(
            is_visible=True,
            approved=True,
            donation__payment__date__gt=datetime.date.today() - datetime.timedelta(days=DISPLAY_DONOR_DAYS),
        ).annotate(donated_amount=models.Sum('donation__payment__amount'))
        return donors.order_by('-donated_amount', 'name')


class FundraisingModel(models.Model):
    id = models.CharField(max_length=12, primary_key=True)
    created = models.DateTimeField(default=timezone.now)
    modified = models.DateTimeField(default=timezone.now)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.modified = timezone.now()
        if not self.id:
            self.id = crypto.get_random_string(length=12)
        return super().save(*args, **kwargs)


class DjangoHero(FundraisingModel):
    email = models.EmailField(blank=True)
    stripe_customer_id = models.CharField(max_length=100, blank=True)
    logo = ImageField(upload_to="fundraising/logos/", blank=True)
    url = models.URLField(blank=True, verbose_name='URL')
    name = models.CharField(max_length=100, blank=True)
    location = models.CharField(max_length=255, blank=True)
    HERO_TYPE_CHOICES = (
        ('individual', 'Individual'),
        ('organization', 'Organization'),
    )
    hero_type = models.CharField(max_length=30, choices=HERO_TYPE_CHOICES, blank=True)
    is_visible = models.BooleanField(
        default=False,
        verbose_name="Agreed to displaying on the fundraising page?",
    )
    is_subscribed = models.BooleanField(
        default=False,
        verbose_name="Agreed to being contacted by DSF?",
    )
    approved = models.NullBooleanField(
        verbose_name="Name, URL, and Logo approved?",
    )

    objects = DjangoHeroManager()

    def __str__(self):
        return self.name if self.name else 'Anonymous #{}'.format(self.pk)

    class Meta:
        verbose_name = "Django hero"
        verbose_name_plural = "Django heroes"

    @property
    def display_name(self):
        return self.name

    @property
    def thumbnail(self):
        return get_thumbnail(self.logo, '170x170', quality=100) if self.logo else None

    @property
    def name_with_fallback(self):
        return self.name if self.name else 'Anonymous Hero'


class Donation(FundraisingModel):
    interval = models.CharField(max_length=20, choices=INTERVAL_CHOICES, blank=True)
    subscription_amount = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)
    donor = models.ForeignKey(DjangoHero, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=100, blank=True)
    stripe_customer_id = models.CharField(max_length=100, blank=True)
    receipt_email = models.EmailField(blank=True)

    def __str__(self):
        return '{} from {}'.format(self.get_interval_display(), self.donor)

    def get_absolute_url(self):
        return reverse('fundraising:thank-you', kwargs={'donation': self.id})

    def is_active(self):
        return bool(self.stripe_subscription_id)
    is_active.boolean = True

    def total_payments(self):
        return self.payment_set.aggregate(models.Sum('amount'))['amount__sum']


class Payment(models.Model):
    donation = models.ForeignKey(Donation, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=9, decimal_places=2, null=True)
    stripe_charge_id = models.CharField(max_length=100, unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '${}'.format(self.amount)


class Testimonial(models.Model):
    author = models.CharField(max_length=255)
    body = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.author


class InKindDonor(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(blank=True, verbose_name='URL')
    description = models.TextField()
    logo = ImageField(upload_to='fundraising/logos/', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'in-kind hero'
        verbose_name_plural = 'in-kind heroes'

    @property
    def display_name(self):
        return self.name

    @property
    def thumbnail(self):
        return get_thumbnail(self.logo, '170x170', quality=100) if self.logo else None


@receiver(post_save, sender=DjangoHero)
@receiver(post_save, sender=InKindDonor)
def create_thumbnail_on_save(sender, **kwargs):
    return kwargs['instance'].thumbnail

fundraising/views.py
import decimal
import json

import stripe
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.forms.models import modelformset_factory
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from .exceptions import DonationError
from .forms import DjangoHeroForm, DonationForm, PaymentForm
from .models import (
    LEADERSHIP_LEVEL_AMOUNT, DjangoHero, Donation, Payment, Testimonial,
)


def index(request):
    testimonial = Testimonial.objects.filter(is_active=True).order_by('?').first()
    return render(request, 'fundraising/index.html', {
        'testimonial': testimonial,
    })


@require_POST
def donate(request):
    form = PaymentForm(request.POST)

    if form.is_valid():
        # Try to create the charge on Stripe's servers - this will charge the user's card
        try:
            donation = form.make_donation()
        except DonationError as donation_error:
            data = {
                'success': False,
                'error': str(donation_error),
            }
        else:
            data = {
                'success': True,
                'redirect': donation.get_absolute_url(),
            }
    else:
        data = {
            'success': False,
            'error': form.errors.as_json(),
        }
    return JsonResponse(data)


def thank_you(request, donation):
    donation = get_object_or_404(Donation, pk=donation)
    if request.method == 'POST':
        form = DjangoHeroForm(
            data=request.POST,
            files=request.FILES,
            instance=donation.donor,
        )

        if form.is_valid():
            form.save()
            messages.success(request, "Thank you! You're a Hero.")
            return redirect('fundraising:index')
    else:
        form = DjangoHeroForm(instance=donation.donor)

    return render(request, 'fundraising/thank-you.html', {
        'donation': donation,
        'form': form,
        'leadership_level_amount': LEADERSHIP_LEVEL_AMOUNT,
    })


@never_cache
def manage_donations(request, hero):
    hero = get_object_or_404(DjangoHero, pk=hero)
    recurring_donations = hero.donation_set.exclude(stripe_subscription_id='')
    past_payments = Payment.objects.filter(donation__donor=hero).select_related('donation')

    ModifyDonationsFormset = modelformset_factory(Donation, form=DonationForm, extra=0)

    if request.method == 'POST':
        hero_form = DjangoHeroForm(
            data=request.POST,
            files=request.FILES,
            instance=hero,
        )
        modify_donations_formset = ModifyDonationsFormset(
            request.POST,
            queryset=recurring_donations
        )

        if hero_form.is_valid() and modify_donations_formset.is_valid():
            hero_form.save()
            modify_donations_formset.save()
            messages.success(request, "Your information has been updated.")
    else:
        hero_form = DjangoHeroForm(instance=hero)
        modify_donations_formset = ModifyDonationsFormset(
            queryset=recurring_donations
        )

    return render(request, 'fundraising/manage-donations.html', {
        'hero': hero,
        'hero_form': hero_form,
        'modify_donations_formset': modify_donations_formset,
        'recurring_donations': recurring_donations,
        'past_payments': past_payments,
        'stripe_publishable_key': settings.STRIPE_PUBLISHABLE_KEY,
    })


@require_POST
def update_card(request):
    donation = get_object_or_404(Donation, id=request.POST['donation_id'])
    try:
        customer = stripe.Customer.retrieve(donation.stripe_customer_id)
        subscription = customer.subscriptions.retrieve(donation.stripe_subscription_id)
        subscription.source = request.POST['stripe_token']
        subscription.save()
    except stripe.error.StripeError as e:
        data = {'success': False, 'error': str(e)}
    else:
        data = {'success': True}
    return JsonResponse(data)


@require_POST
def cancel_donation(request, hero):
    donation_id = request.POST.get('donation')
    hero = get_object_or_404(DjangoHero, pk=hero)
    donations = hero.donation_set.exclude(stripe_subscription_id='')
    donation = get_object_or_404(donations, pk=donation_id)

    customer = stripe.Customer.retrieve(donation.stripe_customer_id)
    customer.subscriptions.retrieve(donation.stripe_subscription_id).delete()

    donation.stripe_subscription_id = ''
    donation.save()

    messages.success(request, "Your donation has been canceled.")
    return redirect('fundraising:manage-donations', hero=hero.pk)


@require_POST
@csrf_exempt
def receive_webhook(request):
    try:
        data = json.loads(request.body.decode())
    except ValueError:
        return HttpResponse(422)

    # For security, re-request the event object from Stripe.
    try:
        event = stripe.Event.retrieve(data['id'])
    except stripe.error.InvalidRequestError:
        return HttpResponse(422)

    return WebhookHandler(event).handle()


class WebhookHandler:
    def __init__(self, event):
        self.event = event

    def handle(self):
        handlers = {
            'invoice.payment_succeeded': self.payment_succeeded,
            'invoice.payment_failed': self.payment_failed,
            'customer.subscription.deleted': self.subscription_cancelled,
        }
        handler = handlers.get(self.event.type, lambda: HttpResponse(422))
        return handler()

    def payment_succeeded(self):
        invoice = self.event.data.object
        # Ensure we haven't already processed this payment
        if Payment.objects.filter(stripe_charge_id=invoice.charge).exists():
            # We need a 2xx response otherwise Stripe will keep trying.
            return HttpResponse()
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)
        amount = decimal.Decimal(invoice.total) / 100
        if invoice.charge:
            donation.payment_set.create(amount=amount, stripe_charge_id=invoice.charge)
        return HttpResponse(status=201)

    def subscription_cancelled(self):
        subscription = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=subscription.id)
        donation.stripe_subscription_id = ''
        donation.save()

        mail_text = render_to_string(
            'fundraising/email/subscription_cancelled.txt', {'donation': donation})
        send_mail('Payment cancelled', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

    def payment_failed(self):
        invoice = self.event.data.object
        donation = get_object_or_404(
            Donation, stripe_subscription_id=invoice.subscription)

        mail_text = render_to_string(
            'fundraising/email/payment_failed.txt', {'donation': donation})
        send_mail('Payment failed', mail_text,
                  settings.DEFAULT_FROM_EMAIL, [donation.donor.email])

        return HttpResponse(status=204)

djangoproject/templates/fundraising/campaign.html
{% extends 'base.html' %}
{% load fundraising_extras humanize static thumbnail %}

{% block title %}Support Django{% endblock %}
{% block layout_class %}full-width{% endblock %}

{% block header %}
<h1 class="visuallyhidden">Support Django</h1>
<p><em>Support Django development</em> by donating to the <em>Django Fellowship</em> program.</p>
{% endblock %}

{% block content %}
{% if messages %}
  {% for message in messages %}
  <h1>{{ message }}</h1>
  {% endfor %}
  <hr>
{% endif %}

<h1>Support the Django Fellowship Program!</h1>

<div class="fundraising-index" id="donate">
  <div class="fundraising-heart" data-percent="{{ donated_amount|as_percentage:campaign.goal }}">
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 503 431">
      <switch>
        <g transform="translate(4, 2)" id="pixels">
          <path d="M 71 0 L 213 0 L 213 71 L 284 71 L 284 0 L 426 0 L 426 71 L 497 71 L 497 213 L 426 213 L 426 284 L 355 284 L 355 355 L 284 355 L 284 426 L 213 426 L 213 355 L 142 355 L 142 284 L 71 284 L 71 213 L 0 213 L 0 71 L 71 71 L 71 0" fill="#f8f8f8" stroke="#c0c0c0" stroke-width="1" />
        </g>
        <foreignObject>
          <img src="{% static 'img/fundraising-heart.png' %}" />
        </foreignObject>
      </switch>
    </svg>
  </div>
  <div class="description">
    <h2>{{ campaign.name }}</h2>
    <ul>
      <li><strong>{{ donated_amount|as_percentage:campaign.goal }}% funded</strong></li>
      <li><strong>${{ donated_amount|intcomma }} donated</strong> of US&nbsp;${{ campaign.goal|intcomma }} goal</li>
      {% if campaign.stretch_goal %}
        <li><strong>US&nbsp;${{ campaign.stretch_goal|intcomma }} <a href="{{ campaign.stretch_goal_url }}">stretch goal</a></strong></li>
      {% endif %}
      <li><strong>{{ total_donors }} donor{{ total_donors|pluralize:",s" }}</strong></li>
    </ul>

    <div class="donate">
      <form method="get" action="{% url "fundraising:donate" %}">
        <h3>Help us make it happen:</h3>
        {{ form.amount }}
        {% if request.GET.campaign %}
        {{ form.campaign }}
        {% endif %}
        <div class="custom-donation">
          <span class="prefix">US $</span>
        </div>
        <input type="submit" value="Donate" class="cta" />
      </form>
    </div>
  </div>
  <div class="cls"></div>
  <p class="footnote">
    Your logo will be visible below if you contribute at least
    US&nbsp;${{ display_logo_amount|intcomma }}.
</p>
</div>

<hr style="margin: 40px 0" />

<h1>About the program</h1>
<p>Django Fellowship is a project where paid contractors are engaged to manage
  some of the administrative and community management tasks of the Django
  project to support rapid development of Django itself. </p>

<p><strong>The first three months of the Django Fellowship program have been very successful.</strong>
  In this short time, <a href="#about">two Django Fellows</a>, one full-time and one part-time, worked on
  around 240 pull requests (including reviewing some of the major features that will
  be in <a href="/weblog/2015/jan/16/django-18-alpha-1-released/">Django 1.8</a>), triaged at
  least 90 different tickets, and made around 200 commits in total! You can read
  <a href="/weblog/2015/jan/21/django-fellowship-retrospective/">the retrospective
  on the things that have been accomplished</a> on our blog.</p>

<h1>We need your help!</h1>

<p>The program has already had a major positive impact on how Django is developed
   and maintained. Release blocking and severe bugs are not postponed indefinitely. Django
   Fellows are a resource to help review patches and contributions from the community, and
   the community loves that:</p>

   {% if testimonial %}
   <blockquote>
     {{ testimonial.body|linebreaks }}
     <em>{{ testimonial.author }}</em>
   </blockquote>
   {% endif %}

<p><strong>If you use Django on a daily basis and care about the development of Django
   itself, you should donate today</strong> (may be <a href="/foundation/donate/#tax-deductible">tax deductible</a>).
   Only with your support can we make sure that the Web framework you base your work on
   can grow to be even better in the coming years.</p>

<p>The weekly cost of the program is about US&nbsp;$2,800.00. <strong>We're
   trying to raise an initial US&nbsp;${{ campaign.goal|intcomma }} to renew the program
   for at least three months, after which we'll endeavor to raise funds on a
   weekly basis to sustain the program.</strong></p>

<p><a href="/weblog/2015/jan/21/django-fellowship-retrospective/">Learn more
   about the Django Fellowship program</a>.</p>

<hr style="margin: 40px 0" />

<div class="heros-section">
  <h1>Django Heroes</h1>
  <p>We're incredibly grateful to everyone who donated to make this happen. We
  couldn't possibly do it without the continuous support from the community.</p>

  <div class="heros">
    {% for donor in donors_with_logo %}
      <div class="hero">
        <div class="hero-logo">
          {% if donor.url %}<a href="{{ donor.url }}" rel="nofollow">{% endif %}
          <img src="{% if donor.logo %}{{ donor.thumbnail.url }}{% else %}{% static 'img/fundraising-heart.png' %}{% endif %}"
            data-src-2x="{% if donor.logo %}{{ donor.thumbnail.url|resolution:'2x' }}{% else %}{% static 'img/fundraising-heart.png' %}{% endif %}"
            alt="{{ donor.name }}" />
          {% if donor.url %}</a>{% endif %}
        </div>
        <div class="hero-name">
          {% if donor.url %}<a href="{{ donor.url }}" rel="nofollow">{% endif %}{% spaceless %}
            {{ donor.name_with_fallback }}
          {% endspaceless %}{% if donor.url %}</a>{% endif %}
          {% if donor.is_amount_displayed %}
            <br/><em>${{ donor.donated_amount|intcomma }}</em>
          {% endif %}
        </div>
    </div>
    {% endfor %}
  </div>
  <div class="heros">
    {% for donor in other_donors %}
      <div class="no-logo-hero">
        {% if donor.url %}<a href="{{ donor.url }}" rel="nofollow">{% endif %}{% spaceless %}
        <span>{{ donor.name_with_fallback }}</span>
        {% endspaceless %}{% if donor.url %}</a>{% endif %}
        {% if donor.is_amount_displayed %}
          <br/><em>${{ donor.donated_amount|intcomma }}</em>
        {% endif %}
      </div>
    {% endfor %}
  </div>

</div>

{% endblock %}

{% block content-extra %}
  <div class="layout-tertiary" id="about">
    <div class="container">
        <h2>What is the Django Software Foundation?</h2>
        <p>Development of Django is supported by an independent foundation
          established as a 501(c)(3) non-profit. Like most open-source foundations,
          the goal of the <a href="/foundation/">Django Software Foundation</a>
          is to promote, support, and advance the Django Web framework. If you're
          interested in how the Django Software Foundation supports the Django
          Web framework, we published a
          <a href="/weblog/2015/jan/08/django-software-foundation-2014/">Summary
          of 2014. </a>
        </p>

        <h2>Who were the Django Fellows?</h2>
        <p>The two Fellows for the duration of the pilot were:</p>
        <p><strong>Tim Graham</strong> - a member of the core team for several years. For
        the 12 months before the fellowship began, he was a major contributor,
        reviewing and merging pull requests. Tim was contracted as a full-time
        Fellow for the duration of the 3 month pilot.</p>
        <p><strong>Berker Peksağ</strong> - a core developer on CPython, Gunicorn, and
        Hylang. In the Django community, he had submitted a few patches, as
        well as organized a Django sprint in Istanbul. During the 3 month pilot,
        Berker supported Tim part-time.</p>
        <p>If the program is renewed, there will be a new application period
        for the next fellow(s).</p>
    </div>
  </div>
{% endblock %}

djangoproject/templates/fundraising/donation_snippet.html
{% load humanize static %}

{% if donation %}
  <div class="fundraising-sidebar">
    <h2>Support Django!</h2>

    <div class="small-heart">
      <img src="{% static "img/small-fundraising-heart.png" %}" alt="Support Django!" />
    </div>

    <div class="small-cta">
      <ul class="list-links-small">
        <li><a href="{% url "fundraising:index" %}">
          {% firstof donation.name "Someone" %} donated
          {% if donation.is_amount_displayed %}US&nbsp;${{ donation.donated_amount|intcomma }}{% endif %}
          for the Django Fellowship program to support Django development.
          Donate today!
        </a></li>
      </ul>
    </div>
  </div>
{% endif %}

djangoproject/templates/fundraising/recurring.html
{% extends 'fundraising/index.html' %}
{% load fundraising_extras humanize static %}

{% block content %}
{% if messages %}
  {% for message in messages %}
  <h1>{{ message }}</h1>
  {% endfor %}
  <hr>
{% endif %}

<h1>Support the Django Software Foundation!</h1>

{% recurring_donation_form %}

<h2>About the Django Software Foundation</h2>

<p>Development of Django is supported by an independent foundation
  established as a 501(c)(3) non-profit. Like most open-source foundations,
  the goal of the <a href="/foundation/">Django Software Foundation</a>
  is to promote, support, and advance the Django Web framework. If you're
  interested in how the Django Software Foundation supports the Django
  Web framework, we published a
  <a href="/weblog/2015/jan/08/django-software-foundation-2014/">Summary
  of 2014.</a>
</p>

<h2>Django Fellowship Program</h2>

<p>The biggest expense of the DSF is the Django Fellowship program. It's a
  project where paid contractors are engaged to manage some of the
  administrative and community management tasks of the Django project to
  support rapid development of Django itself.</p>

<p><strong>The first three months of the Django Fellowship program were very successful.</strong>
  In this short time, two Django Fellows, one full-time and one part-time, worked on
  around 240 pull requests (including reviewing some of the major features that
  are in <a href="https://docs.djangoproject.com/en/stable/releases/1.8/">Django 1.8</a>),
  triaged at least 90 different tickets, and made around 200 commits in total!
  You can read <a href="/weblog/2015/jan/21/django-fellowship-retrospective/">
  the retrospective on the things that have been accomplished</a> on our blog.</p>

<p>The program was renewed in March 2015 after the initial fundraising efforts
   to renew the program succeeded.</P>

<h2>We need your help!</h2>

<p>The program has a major positive impact on how Django is developed and
   maintained. Release blocking and severe bugs are not postponed indefinitely.
   Django Fellows are a resource to help review patches and contributions from
   the community, and the community loves that!</p>

<p><strong>If you use Django on a daily basis and care about the development of
   Django itself, you should donate today</strong> (may be
   <a href="/foundation/donate/#tax-deductible">tax deductible</a>). Only with
   your support can we make sure that the Web framework you base your work on
   can grow to be even better in the coming years.</p>

<hr/>

<div class="heros-section">
  <h2>Django Heroes</h2>
  <p>We're incredibly grateful to everyone who donates to make this happen. We
  couldn't possibly do it without the continuous support from the community.</p>

  {% display_recurring_django_heros %}

</div>

{% endblock %}